spring:
  cloud:
    stream:
      function:
        definition: processNumber;processLetter
      kafka:
        binder:
          brokers: localhost:9092
          required-acks: 1
          auto-create-topics: true
          consumer-properties:
            auto.offset.reset: earliest
            max.poll.records: 1
      bindings:
        processNumber-in-0:
          destination: numbers    # The actual Kafka topic name
          group: number-consumer-group
          consumer:
            autoStartup: true
        processLetter-in-0:
          destination: letters    # The actual Kafka topic name 
          group: letter-consumer-group
          consumer:
            autoStartup: true
      default-binder: kafka
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    org.springframework.cloud.stream: DEBUG
    com.example.kafkastream: DEBUG

server:
  port: 8080